### ISSUE TITLE
preklady nove modely

### ISSUE THREAD

**Issue by Visgean** [WebarchivCZ/Seeder#369]
v seederu vidím, že ještě není celé přeložené do češtiny, aktuálně tam mám

    Topic collections - Tematické kolekce
    title - název
    created - vytvořeno
    Last Changed - poslední změna

když chci přidat novou kolekci, tak

    něco je stále v angličtině (title (název), annotation (anotace), image (obrázek), keywords (klíčová slova), attachements (přílohy), All sources are under open license or contract (Všechny zdroje jsou pod CC nebo mají smlouvu))

**Comment by mariehaskovcova** [comment]
v Seederu jsou anglické názvy (viz komentář nahoře), které ale v Transifexu není možné přeložit (tam aktuálně zůstávají k přeložení jen 2 slova - viz obr.) Všechny ostatní názvy v AJ bychom potřebovali zanést do Transifexu, díky

![transifex](https://cloud.githubusercontent.com/assets/19947819/24617104/5540e202-1893-11e7-876b-9105168db525.png)

**Comment by Visgean** [comment]
@westfood  poustel si  ``push_locales.sh``?

**Comment by westfood** [comment]
Hele.. 

mám to takhle, ale koukám že makemessages -a, jsem nikde neměl.. tak to přidám..

```
- name: Django manage
  django_manage:
    app_path: "{{ seeder_home }}/Seeder"
    virtualenv: "{{ seeder_virtualenv }}"
    command: "{{ item }}"
  with_items:
  - "migrate"
  - "collectstatic --noinput"
  - "search_blob_initialize"
  - "compilemessages"
  - "crontab add"
  - "legacy_sync_screenshots"
  tags: update
  become_user: "{{ seeder_user }}"
```
mám crona na pull
```
- name: "at 7:40, 12:40, 16:40, 20:40, 23:40 transifex client pulls tranlastion and manage.py runs compilemessages"
  cron:
    name: transiflex pull translation and manage compilemessages
    job: "cd {{ seeder_home }}/Seeder && {{ seeder_virtualenv }}/bin/tx pull -a && {{ seeder_virtualenv }}/bin/python {{ seeder_home }}/Seeder/manage.py compilemessages"
    hour: "7,12,16,20,23"
    minute: 40
  tags: translation
  become_user: "{{ seeder_user }}"
```
